package com.weacadt.log.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.weacadt.log.data.TodoItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TODO_ITEM".
*/
public class TodoItemDao extends AbstractDao<TodoItem, Long> {

    public static final String TABLENAME = "TODO_ITEM";

    /**
     * Properties of entity TodoItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Order = new Property(1, Long.class, "order", false, "Order");
        public final static Property Thing = new Property(2, String.class, "thing", false, "THING");
        public final static Property IsDone = new Property(3, boolean.class, "isDone", false, "IS_DONE");
        public final static Property Year = new Property(4, int.class, "year", false, "YEAR");
        public final static Property Month = new Property(5, int.class, "month", false, "MONTH");
        public final static Property DayOfMonth = new Property(6, int.class, "dayOfMonth", false, "DAY_OF_MONTH");
    }


    public TodoItemDao(DaoConfig config) {
        super(config);
    }
    
    public TodoItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TODO_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"Order\" INTEGER," + // 1: order
                "\"THING\" TEXT," + // 2: thing
                "\"IS_DONE\" INTEGER NOT NULL ," + // 3: isDone
                "\"YEAR\" INTEGER NOT NULL ," + // 4: year
                "\"MONTH\" INTEGER NOT NULL ," + // 5: month
                "\"DAY_OF_MONTH\" INTEGER NOT NULL );"); // 6: dayOfMonth
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TODO_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TodoItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long order = entity.getOrder();
        if (order != null) {
            stmt.bindLong(2, order);
        }
 
        String thing = entity.getThing();
        if (thing != null) {
            stmt.bindString(3, thing);
        }
        stmt.bindLong(4, entity.getIsDone() ? 1L: 0L);
        stmt.bindLong(5, entity.getYear());
        stmt.bindLong(6, entity.getMonth());
        stmt.bindLong(7, entity.getDayOfMonth());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TodoItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long order = entity.getOrder();
        if (order != null) {
            stmt.bindLong(2, order);
        }
 
        String thing = entity.getThing();
        if (thing != null) {
            stmt.bindString(3, thing);
        }
        stmt.bindLong(4, entity.getIsDone() ? 1L: 0L);
        stmt.bindLong(5, entity.getYear());
        stmt.bindLong(6, entity.getMonth());
        stmt.bindLong(7, entity.getDayOfMonth());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TodoItem readEntity(Cursor cursor, int offset) {
        TodoItem entity = new TodoItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // order
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // thing
            cursor.getShort(offset + 3) != 0, // isDone
            cursor.getInt(offset + 4), // year
            cursor.getInt(offset + 5), // month
            cursor.getInt(offset + 6) // dayOfMonth
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TodoItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrder(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setThing(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsDone(cursor.getShort(offset + 3) != 0);
        entity.setYear(cursor.getInt(offset + 4));
        entity.setMonth(cursor.getInt(offset + 5));
        entity.setDayOfMonth(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TodoItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TodoItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TodoItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
